# Generated by Django 3.0 on 2022-12-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20221213_1214'),
        ('profiles', '0002_auto_20221213_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
